spring:
  config:
    import: file:env.properties
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/${DB_DATABASE}
    username: ${DB_USER}
  jpa:
    hibernate:
      ddl-auto: update
  spring:
    jpa:
      show-sql: true
